### PR TITLE
Add account immutable Namespace and optional Label

### LINKED ISSUE #42: [Wallet repos] Prevent indexing accounts by name
At the moment the name of an account is used in the wallet repos as (primary) key to identify them in the storage.

This basically prevents the user to be allowed to change the name of an account but this is a feature we might want to add in combo with wallet restoration: in such a situation, it's possible that the user doesn't know or remember some or all the wallet accounts, therefore, ocean would assign some default name to the restored accounts. 
I think it would be handful for the user to have an rpc like `ChangeAccountName({ old_name, new_name })` so the account's name can be changed just like it was nothing more than a label.

At the moment this is not possible because in every wallet repo implementation the account's name is used as its identifier, making such change hard to implement. The idea would be to use only the account index as identifier and "downgrade" the name as info just like the derivation path or any other domain.WalletAccount field.

### LINKED ISSUE #44: Account namespace and label
Following the discussion of #42, we should update the protos by renaming the `Name` field of the `Create*Account` request message to `Label` and make it optional in the service instead of being required.
Also, we should update the response message by returning the `AccountInfo` of the newly created account.

Internally, we should rename the related domain's actual `Name` field to `Label` and add a new one `Namespace`.

The namespace is something immutable and assigned by the service to every account. It could be a string like `<root_path_purpose>-account-<derivation index>`, for example `84-account-0` for account 0 of wallet with root path `m/84'/<network>'`. The namespace must be used by the repo to identify an account uniquely.

The label, instead, is something mutable and set by the user optionally. If a label is set, the user/client can refer to the account with it, otherwise the namespace must be used.

We should add also a new rpc `SetAccountLabel` to allow one to change account label at will.

### PR DESCRIPTION
**Pull request by altafan**
This adds an immutable and non-null `Namespace` for the wallet account, generated automatically by ocean with the format `bip<root_path_purpose>-account<index>`. This field is used internally to refer to wallet accounts, like for example in utxo or transaction domains.

This also adds a mutable and nullable field `Label` field that the user can set when creating a wallet account or later with the a brand new `SetAccountLabel` API.

The user can use either the namespace or the label (if set) to refer to a wallet account in all other APIs.

Closes #42.
Closes #44.

NOTE: this includes an hotfix in electrum blockchain scanner to prevent race conditions. Credits to @sekulicd who discovered this in #45.

Please @tiero @sekulicd review this.

### CODE REVIEW

**Review by sekulicd — COMMENTED** [review]
Honestly I found this as worse version compared to rejected [PR45](https://github.com/vulpemventures/ocean/pull/45) and here are few reasons:
1. DB layer:
   1.1 We didnt add new migration file, with new changes, but update existing one, this means we need to destroy/recreate already deployed DB's which is maybe not critical if we are not in testnet/prod
   1.2 We didnt make relations to the other tables(tx_input_account, utxo) which lowers integrity of db data
   1.3 label in account table is not unique and it is referenced in DELETE query which means one could delete many account if those have same name
2. Inconsistency: We wanted to give user option to reference account name with label or namespace throughout different APIs and that is ok, however having same var name meaning different stuff in code base is something i found problematic for eg:
In init.sql we have account_name in utxo table which is actually namespace, in wallet_repository CreateAccount accepts arg account_name which is actually label and blockchain scanner has WatchForAccount method that also accepts account_name which is actually namespace, so there is hidden stuff for developer and one would need to go and check other code to find correct argument
 3. Also testing was improved in rejected PR, and these changes were introduced with necessity as adding references to other tables required more job for preparing/cleaning tests for DB, and this preparation/cleaning can be different for different repos, also it had sanity test(kind of end to end)
 
 As stated [here](https://github.com/vulpemventures/ocean/pull/45#issuecomment-1404057244) PR was closed as it "contains too many unnecessary changes" but they were added for above reasons, naming consistency and more flexible/error prone testing.

This is just my opinion, and if you decide to go with current changes i think you should at least take into consideration points 1.1 and 1.3

@tiero @altafan

**Comment by altafan** [comment]
> 2. Inconsistency: We wanted to give user option to reference account name with label or namespace throughout different APIs and that is ok, however having same var name meaning different stuff in code base is something i found problematic

I don't think we can talk about inconsistency if variables are named differently in components.

I didn't make such changes in scanners, repos, etc. to prevent having tons of files modified only for some variable naming, which is not really important. After all, if the code is well written, a change of a variable name should not be so confusing.

**Comment by altafan** [comment]
> 3. Also testing was improved in rejected PR, and these changes were introduced with necessity as adding references to other tables required more job for preparing/cleaning tests for DB, and this preparation/cleaning can be different for different repos, also it had sanity test(kind of end to end)

Again, even if I appreciated the effort, it's not part of the scope of this PR and should be done in a dedicated PR by prior discussing on how to make the changes.

**Comment by altafan** [comment]
> 1.3 label in account table is not unique and it is referenced in DELETE query which means one could delete many account if those have same name

Reverted changes to DeleteAccount query.

**Comment by sekulicd** [comment]
> I opted for this solution since we don't have any service using ocean in prod yet. But anyway, I was wondering if adding new migration files was enough: what happens if an existing ocean wallet's db that has several records with old table format and Name field and gets updated? Are those record updated accordingly? Are they somehow corrupted after the table update?

Purpose is to keep existing data and add new things(columns, constraints etc)

**Comment by altafan** [comment]
> Purpose is to keep existing data and add new things(columns, constraints etc)

But the existing account records with deprecated Name field would not be supported anymore. I think this should be something handled by the migration somehow.

**Pull request merged**
